# Generated by Django 2.1.1 on 2019-11-24 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('pname', models.CharField(blank=True, max_length=100)),
                ('domain', models.CharField(max_length=100, null=True)),
                ('summary', models.TextField(null=True)),
                ('subject', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('CS', 'Computer Science'), ('IS', 'Information Science'), ('EC', 'Electronics'), ('CIVIL', 'Civil'), ('MECH', 'mechanical'), ('EEE', 'eee'), ('IE', 'ie'), ('TC', 'TC')], max_length=50)),
                ('pfile', models.FileField(max_length=1000, null=True, upload_to='home/pfiles')),
                ('sem', models.IntegerField(null=True)),
                ('project_pic', models.ImageField(default='home/images/dummyimage.PNG', upload_to='home/images')),
                ('types', models.CharField(choices=[('Sy', 'synopis'), ('Re', 'report')], max_length=5)),
                ('status', models.CharField(choices=[('A', 'accepted'), ('R', 'rejected'), ('M', 'modify'), ('U', 'unseen')], default='U', max_length=5)),
                ('likes', models.IntegerField(null=True)),
                ('best_project', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=5)),
                ('tcomment', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=100)),
                ('sem', models.IntegerField(null=True)),
                ('department', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100, null=True)),
                ('yearsofexperience', models.IntegerField(null=True)),
                ('position', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
        ),
        migrations.AddField(
            model_name='project',
            name='teacher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Teacher'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
        ),
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Project'),
        ),
        migrations.AddField(
            model_name='comment',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Teacher'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
