# Generated by Django 2.0.8 on 2019-11-03 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100, null=True)),
                ('summary', models.TextField(null=True)),
                ('subject', models.CharField(max_length=100)),
                ('types', models.CharField(choices=[('Sy', 'synopis'), ('Re', 'report')], max_length=5)),
                ('status', models.CharField(choices=[('A', 'accepted'), ('R', 'rejected'), ('M', 'modify'), ('U', 'unseen')], default='U', max_length=5)),
                ('comment', models.TextField(null=True)),
                ('likes', models.IntegerField(null=True)),
                ('best_project', models.IntegerField(choices=[('Y', 'Yes'), ('N', 'No')], default='N')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usn', models.CharField(max_length=100)),
                ('sname', models.CharField(max_length=100, null=True)),
                ('sem', models.CharField(max_length=100, null=True)),
                ('department', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100, null=True)),
                ('yearsofexperience', models.IntegerField(null=True)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
        ),
        migrations.AddField(
            model_name='project',
            name='teacher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Teacher'),
        ),
    ]
