# Generated by Django 2.1.1 on 2019-11-24 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Student',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='teacher',
        ),
    ]
