# Generated by Django 2.0.8 on 2019-11-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='best_project',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=5),
        ),
    ]
