# Generated by Django 2.0.8 on 2019-11-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191103_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(default='home/images/dummyimage.PNG', upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='project',
            name='sem',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.IntegerField(null=True),
        ),
    ]
